### ISSUE TITLE
May require 'docker login' error?

### ISSUE THREAD

**Issue by ryanmclaughlin** [AbenezerMamo/crypto-signal#99] opened 2018-01-22 04:55 UTC
Hi, I'm attempting to use `docker-compose up` and I'm getting `ERROR: pull access denied for crypto-signal, repository does not exist or may require 'docker login'` I've tried `docker login` and logged in but i'm still getting the same error.

**Comment by shads2** [comment] 2018-01-22 05:19
Currently you need to build the image locally by running `make build` we don't have a public docker image available _yet_.

**Comment by ryanmclaughlin** [comment] 2018-01-22 06:11
@shads2 Thanks! Sorry about that. So I've successfully built a local image using `make build` and using `docker-compose up` to run it. I get this now:

```
app_1  | Traceback (most recent call last):
app_1  |   File "app.py", line 11, in <module>
app_1  |     from behaviour import Behaviour
app_1  |   File "/app/behaviour.py", line 8, in <module>
app_1  |     from analysis import StrategyAnalyzer
app_1  |   File "/app/analysis.py", line 7, in <module>
app_1  |     import pandas
app_1  |   File "/usr/local/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
app_1  |     "Missing required dependencies {0}".format(missing_dependencies))
app_1  | ImportError: Missing required dependencies ['numpy']
```

**Comment by shads2** [comment] 2018-01-22 06:51
That is bizarre, but I can't replicate the behaviour just yet... it appears this mornings merge to master appears to have caused some issues. We'll look into it.

**Comment by shads2** [comment] 2018-01-22 08:17
I have resolved the problems on master, but I am still unable to replicate your issue, I am currently stumped as to how this could be occurring. I will continue to experiment but this may take a little longer to work out what the root cause is. What docker version and image sha of the python 3.6 container are you using?

**Comment by mboncalo** [comment] 2018-01-23 14:27
Hi Ryan,
try the folowing command to install numpy
pip install numpy==1.14.0
and afterwards install all the requirements:
pip install -r requirements.txt
make sure you have python 3.6 installed
Hope this helps.

**Comment by mboncalo** [comment] 2018-01-23 14:58
Hi Ryan,
How did you install numpy ? Using pip or yum ?

**Comment by shads2** [comment] 2018-01-28 19:17
Due to no further update I am closing this.

**Closed by shads2** 2018-01-28 19:17 UTC
Labels: bug
